"""update_changepassword

Revision ID: 391904a1950a
Revises: d61b8eda995b
Create Date: 2024-10-07 19:06:36.905548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql



# revision identifiers, used by Alembic.
revision: str = '391904a1950a'
down_revision: Union[str, None] = 'd61b8eda995b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('change_password', sa.Column('email', sa.String(), nullable=True))
    op.drop_column('change_password', 'epired_date')
    # ### end Alembic commands ###



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('change_password', sa.Column('epired_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('change_password', 'email')
    # ### end Alembic commands ###
